name: CI
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  main:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        ghc:
          - "8.0"
          - "8.2"
          - "8.4"
          - "8.6"
          - "8.8"
          - "8.10"
          - "9.0"
          - "9.2"
          - "9.4"
          - "9.6"
          - "9.8"
          - "9.10"
        include:
        - os: macOS-latest
          ghc: "9.10"
        - os: windows-latest
          ghc: "9.10"
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - uses: actions/cache@v4
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}
    - name: Cabal version
      run: |
        cabal --version
    - name: Unpack
      run: |
        cabal sdist --ignore-project --output-directory ..
        cd ..
        cabal get syb-*.tar.gz
    - name: Build & Test
      run: |
        cd ../syb-*/
        cabal build all --enable-tests
        cabal test --enable-tests --test-show-details=direct all
    - name: Haddock
      run: |
        cd ../syb-*/
        cabal haddock all
    - name: Cabal check
      run: |
        cd ../syb-*/
        cabal check
